"use strict";
// Auto generated by 'gen-icons.ts'

export interface SVGIcon {
	width: number;
	height: number;
	innerSVG: string;
}

export const icons: { [id: string]: SVGIcon } = {
	window: {
		width: 20,
		height: 20,
		innerSVG:
			'<rect x="2.5" y="2.5" width="15" height="15" class="icon-panel-back"/><rect x="2.5" y="2.5" width="15" height="3" class="icon-panel-title"/><rect x="2.5" y="2.5" width="15" height="15" class="icon-border"/>',
	},
	dockLeft: {
		width: 18,
		height: 18,
		innerSVG:
			'<rect x="2.5" y="2.5" width="13" height="13" style="stroke: #666; fill: none"/><rect x="2.5" y="2.5" width="7" height="13" class="icon-panel-back"/><rect x="2.5" y="2.5" width="7" height="3" class="icon-panel-title"/><rect x="2.5" y="2.5" width="7" height="13" class="icon-border"/>',
	},
	dockRight: {
		width: 18,
		height: 18,
		innerSVG:
			'<rect x="2.5" y="2.5" width="13" height="13" style="stroke: #666; fill: none"/><rect x="8.5" y="2.5" width="7" height="13" class="icon-panel-back"/><rect x="8.5" y="2.5" width="7" height="3" class="icon-panel-title"/><rect x="8.5" y="2.5" width="7" height="13" class="icon-border"/>',
	},
	maximize: {
		width: 18,
		height: 18,
		innerSVG:
			'<rect x="2.5" y="2.5" width="13" height="13" class="icon-panel-back"/><rect x="2.5" y="2.5" width="13" height="3" class="icon-panel-title"/><rect x="2.5" y="2.5" width="13" height="13" class="icon-border"/>',
	},
	float: {
		width: 18,
		height: 18,
		innerSVG:
			'<rect x="2.5" y="2.5" width="13" height="13" style="stroke: #666; fill: none"/><rect x="4.5" y="5.5" width="9" height="8" class="icon-panel-back"/><rect x="4.5" y="5.5" width="9" height="3" class="icon-panel-title"/><rect x="4.5" y="5.5" width="9" height="8" class="icon-border"/>',
	},
	minimize: {
		width: 18,
		height: 18,
		innerSVG:
			'<line x1="3" y1="14.5" x2="15" y2="14.5" class="icon-border" style="stroke-width: 2.5"/>',
	},
	help: {
		width: 18,
		height: 18,
		innerSVG:
			'<path d="M 5,6 A 4,4 0 0 1 10.53,2.3 A 4,4 0 0 1 11.83,8.83 L 9 11.5 L 9 13" class="icon-border" style="stroke-width: 2"/><line x1="9" y1="15" x2="9" y2="17" class="icon-border" style="stroke-width: 2"/>',
	},
	close: {
		width: 18,
		height: 18,
		innerSVG:
			'<line x1="4" y1="4" x2="14" y2="14" class="icon-border" style="stroke-width: 2"/><line x1="4" y1="14" x2="14" y2="4" class="icon-border" style="stroke-width: 2"/>',
	},
	msgBoxQuestion: {
		width: 40,
		height: 40,
		innerSVG:
			'<circle cx="20" cy="20" r="18.5" style="stroke-width: 2; stroke: #04d; fill: #16f"/><path d="M 13,15 A 7,7 0 0 1 22.68,8.53 A 7,7 0 0 1 24.95,19.95 L 20 25 L 20 28" style="stroke-width: 2; stroke: #fff; fill: none"/><line x1="20" y1="31" x2="20" y2="34" style="stroke-width: 2; stroke: #fff; fill: none"/>',
	},
	msgBoxExclamation: {
		width: 40,
		height: 40,
		innerSVG:
			'<polygon points="19,2 21,2 38,36 37,38 3,38 2,36" style="stroke-width: 2; stroke: #a91; fill: #ec2"/><line x1="20" y1="10" x2="20" y2="28" style="stroke-width: 2; stroke: #000; fill: none"/><line x1="20" y1="31" x2="20" y2="34" style="stroke-width: 2; stroke: #000; fill: none"/>',
	},
	newDocument: {
		width: 20,
		height: 20,
		innerSVG:
			'<polygon points="4.5,7.5 8.5,3.5 14.5,3.5 14.5,16.5 4.5,16.5" style="stroke: #333; fill: #fff"/><polyline points="4.5,7.5 8.5,7.5 8.5,3.5" style="stroke: #333; fill: none"/><circle cx="14" cy="14" r="4.75" style="stroke: #030; fill: #0a0"/><line x1="14" y1="17" x2="14" y2="11" style="stroke-width: 2; stroke: #fff; fill: none"/><line x1="11" y1="14" x2="17" y2="14" style="stroke-width: 2; stroke: #fff; fill: none"/>',
	},
	openDocument: {
		width: 20,
		height: 20,
		innerSVG:
			'<polygon points="2.5,4.5 7.5,4.5 9.5,6.5 15.5,6.5 15.5,15.5 2.5,15.5" style="fill: #ec5; stroke: #330"/><polygon points="5.5,8.5 17.5,8.5 15.5,15.5 3.5,15.5" style="fill: #fd6; stroke: #330"/>',
	},
	saveDocument: {
		width: 20,
		height: 20,
		innerSVG:
			'<polygon points="3.5,3.5 16.5,3.5 16.5,16.5 5.5,16.5 3.5,14.5" style="stroke: #139; fill: #36d"/><rect x="7" y="11" width="6" height="5" style="stroke: none; fill: #eef"/><rect x="8" y="12" width="2" height="3" style="stroke: none; fill: #36d"/><rect x="6" y="4" width="8" height="5" style="stroke: none; fill: #fff"/>',
	},
	saveDocumentAs: {
		width: 20,
		height: 20,
		innerSVG:
			'<polygon points="3.5,3.5 16.5,3.5 16.5,16.5 5.5,16.5 3.5,14.5" style="stroke: #139; fill: #36d"/><rect x="7" y="11" width="6" height="5" style="stroke: none; fill: #eef"/><rect x="8" y="12" width="2" height="3" style="stroke: none; fill: #36d"/><rect x="6" y="4" width="8" height="5" style="stroke: none; fill: #fff"/><line x1="8" y1="8" x2="18" y2="18" style="stroke-width: 3; stroke: #0005; fill: none"/><polygon points="8,6 11,7 9,9" style="stroke: none; fill: #fc9"/><polygon points="8,6 9.5,6.5 8.5,7.5" style="stroke: none; fill: #000"/><line x1="10" y1="8" x2="18" y2="16" style="stroke-width: 3; stroke: #000; fill: none"/><line x1="10" y1="8" x2="18" y2="16" style="stroke-width: 2; stroke: #dd0; fill: none"/><polygon points="8,6 9.5,6.5 8.5,7.5" style="stroke: none; fill: #000"/><path d="M 19.06,14.94 A 1.5,1.5 0 0 1 19.06,17.06 A 1.5,1.5 0 0 1 16.94,17.06" style="stroke: none; fill: #000"/><circle cx="18" cy="16" r="1" style="stroke: none; fill: #f33"/>',
	},
	newEditor: {
		width: 20,
		height: 20,
		innerSVG:
			'<polygon points="4.5,7.5 8.5,3.5 14.5,3.5 14.5,16.5 4.5,16.5" style="stroke: #333; fill: #fff"/><polyline points="4.5,7.5 8.5,7.5 8.5,3.5" style="stroke: #333; fill: none"/><line x1="10" y1="15" x2="10" y2="9" style="stroke-width: 2; stroke: #44cc22; fill: none;"/><line x1="7" y1="12" x2="13" y2="12" style="stroke-width: 2; stroke: #44cc22; fill: none;"/>',
	},
	run: {
		width: 20,
		height: 20,
		innerSVG: '<polygon points="5,5 15,10 5,15" class="icon-green-fill"/>',
	},
	interrupt: {
		width: 20,
		height: 20,
		innerSVG:
			'<rect x="5" y="5" width="4" height="10" class="icon-red-fill"/><rect x="11" y="5" width="4" height="10" class="icon-red-fill"/>',
	},
	reset: {
		width: 20,
		height: 20,
		innerSVG:
			'<rect x="5" y="5" width="10" height="10" class="icon-red-fill"/>',
	},
	stepInto: {
		width: 20,
		height: 20,
		innerSVG:
			'<rect x="10" y="3" width="7" height="2" class="icon-neutral-fill"/><rect x="13" y="6" width="4" height="2" class="icon-neutral-fill"/><rect x="13" y="9" width="4" height="2" class="icon-neutral-fill"/><rect x="13" y="12" width="4" height="2" class="icon-neutral-fill"/><rect x="10" y="15" width="7" height="2" class="icon-neutral-fill"/><polyline points="8,4 3,4 3,10 6,10" class="icon-blue-line"/><polygon points="5,7 5,13 9.5,10" class="icon-blue-fill"/>',
	},
	stepOver: {
		width: 20,
		height: 20,
		innerSVG:
			'<rect x="10" y="3" width="7" height="2" class="icon-neutral-fill"/><rect x="13" y="6" width="4" height="2" class="icon-neutral-fill"/><rect x="13" y="9" width="4" height="2" class="icon-neutral-fill"/><rect x="13" y="12" width="4" height="2" class="icon-neutral-fill"/><rect x="10" y="15" width="7" height="2" class="icon-neutral-fill"/><polyline points="8,4 3,4 3,16 6,16" class="icon-blue-line"/><polygon points="5,13 5,19 9.5,16" class="icon-blue-fill"/>',
	},
	stepOut: {
		width: 20,
		height: 20,
		innerSVG:
			'<rect x="10" y="3" width="7" height="2" class="icon-neutral-fill"/><rect x="13" y="6" width="4" height="2" class="icon-neutral-fill"/><rect x="13" y="9" width="4" height="2" class="icon-neutral-fill"/><rect x="13" y="12" width="4" height="2" class="icon-neutral-fill"/><rect x="10" y="15" width="7" height="2" class="icon-neutral-fill"/><polyline points="11,10 3,10 3,16 6,16" class="icon-blue-line"/><polygon points="5,13 5,19 9.5,16" class="icon-blue-fill"/>',
	},
	breakPoint: {
		width: 20,
		height: 20,
		innerSVG: '<circle cx="10" cy="10" r="3.9" class="icon-red-fill"/>',
	},
	search: {
		width: 20,
		height: 20,
		innerSVG:
			'<path d="M 11.54,11.54 A 5,5 0 0 1 4.46,4.46 A 5,5 0 0 1 11.54,11.54 L 17 17" class="icon-neutral-line" style="stroke-width: 1.5"/>',
	},
	export: {
		width: 20,
		height: 20,
		innerSVG:
			'<polygon points="3,7 10,7 10,3 17,10 10,17 10,13 3,13" class="icon-green-frame"/>',
	},
	config: {
		width: 20,
		height: 20,
		innerSVG:
			'<circle cx="10" cy="10" r="2" class="icon-neutral-fill"/><circle cx="10" cy="10" r="5.7" class="icon-neutral-line" style="stroke-width: 2"/><line x1="15.8" y1="11.55" x2="19.08" y2="12.43" class="icon-neutral-line" style="stroke-width: 2"/><line x1="14.24" y1="14.24" x2="16.65" y2="16.65" class="icon-neutral-line" style="stroke-width: 2"/><line x1="11.55" y1="15.8" x2="12.43" y2="19.08" class="icon-neutral-line" style="stroke-width: 2"/><line x1="8.45" y1="15.8" x2="7.57" y2="19.08" class="icon-neutral-line" style="stroke-width: 2"/><line x1="5.76" y1="14.24" x2="3.35" y2="16.65" class="icon-neutral-line" style="stroke-width: 2"/><line x1="4.2" y1="11.55" x2="0.92" y2="12.43" class="icon-neutral-line" style="stroke-width: 2"/><line x1="4.2" y1="8.45" x2="0.92" y2="7.57" class="icon-neutral-line" style="stroke-width: 2"/><line x1="5.76" y1="5.76" x2="3.35" y2="3.35" class="icon-neutral-line" style="stroke-width: 2"/><line x1="8.45" y1="4.2" x2="7.57" y2="0.92" class="icon-neutral-line" style="stroke-width: 2"/><line x1="11.55" y1="4.2" x2="12.43" y2="0.92" class="icon-neutral-line" style="stroke-width: 2"/><line x1="14.24" y1="5.76" x2="16.65" y2="3.35" class="icon-neutral-line" style="stroke-width: 2"/><line x1="15.8" y1="8.45" x2="19.08" y2="7.57" class="icon-neutral-line" style="stroke-width: 2"/>',
	},
	restorePanels: {
		width: 20,
		height: 20,
		innerSVG:
			'<rect x="2.5" y="2.5" width="15" height="15" style="stroke: #aaa; fill: #fff"/><rect x="11" y="3" width="1" height="14" style="stroke: none; fill: #ccc"/><rect x="3" y="3" width="14" height="1" style="stroke: none; fill: #77f"/><rect x="3" y="12" width="8" height="1" style="stroke: none; fill: #77f"/><path d="M 6.67,7.67 A 4,4 0 0 1 13.39,9.57 A 4,4 0 0 1 8.26,14.3" style="stroke: #222; stroke-width: 1.7; fill: none"/><polygon points="5,5 5,10 10,10" style="stroke: none; fill: #222"/>',
	},
	editor: {
		width: 20,
		height: 20,
		innerSVG:
			'<polygon points="4.5,7.5 8.5,3.5 14.5,3.5 14.5,16.5 4.5,16.5" style="stroke: #333; fill: #fff"/><polyline points="4.5,7.5 8.5,7.5 8.5,3.5" style="stroke: #333; fill: none"/><rect x="10" y="5" width="3" height="1" style="stroke: none; fill: #777"/><rect x="10" y="7" width="2" height="1" style="stroke: none; fill: #777"/><rect x="7" y="9" width="4" height="1" style="stroke: none; fill: #777"/><rect x="6" y="11" width="7" height="1" style="stroke: none; fill: #777"/><rect x="9" y="13" width="4" height="1" style="stroke: none; fill: #777"/>',
	},
	messages: {
		width: 20,
		height: 20,
		innerSVG:
			'<path d="M 4.87,13 A 7,6 0 0 1 12.68,3.15 A 7,6 0 0 1 7.97,14.36 L 4.5 17 Z" style="stroke: #222; fill: #fff"/><rect x="8" y="6" width="3" height="1" style="stroke: none; fill: #777"/><rect x="6" y="8" width="2" height="1" style="stroke: none; fill: #777"/><rect x="9" y="8" width="5" height="1" style="stroke: none; fill: #777"/><rect x="7" y="10" width="4" height="1" style="stroke: none; fill: #777"/>',
	},
	stackView: {
		width: 20,
		height: 20,
		innerSVG:
			'<polygon points="4,5.5 10,8.5 16,5.5 10,2.5" style="stroke: none; fill: #fff"/><polygon points="4,5.5 4,14.5 10,17.5 10,8.5" style="stroke: none; fill: #bbb"/><polygon points="10,17.5 16,14.5 16,5.5 10,8.5" style="stroke: none; fill: #999"/><polyline points="3,8.5 10,11.5 17,8.5" style="stroke-width: 0.6; stroke: #222; fill: none"/><polyline points="3,11.5 10,14.5 17,11.5" style="stroke-width: 0.6; stroke: #222; fill: none"/><polyline points="3,14.5 10,17.5 17,14.5" style="stroke-width: 0.6; stroke: #222; fill: none"/><polygon points="3.5,5.3 3.5,5.7 10,8.5 16.5,5.7 16.5,5.3 10,2.5" style="stroke-width: 0.6; stroke: #222; fill: none"/>',
	},
	programView: {
		width: 20,
		height: 20,
		innerSVG:
			'<polygon points="3,2 13,2 13,5 15,5 15,8 17,8 17,12 13,12 13,14 15,14 15,18 5,18 5,15 3,15 3,11 7,11 7,9 5,9 5,6 3,6" style="stroke:none; fill: #eeeeeec0"/><rect x="4" y="3" width="8" height="2" style="stroke:none; fill: #000"/><rect x="6" y="6" width="8" height="2" style="stroke:none; fill: #000"/><rect x="8" y="9" width="8" height="2" style="stroke:none; fill: #000"/><rect x="4" y="12" width="8" height="2" style="stroke:none; fill: #000"/><rect x="6" y="15" width="8" height="2" style="stroke:none; fill: #000"/>',
	},
	turtle: {
		width: 20,
		height: 20,
		innerSVG:
			'<path d="M 11.5,5 A 2,2.5 0 0 1 7.5,5 A 2,2.5 0 0 1 11.5,5 Z" style="stroke: #070; fill: #2c3"/><polyline points="3.5,6 9.5,11 15.5,6" style="stroke-width: 1.6; stroke: #070; fill: none"/><polyline points="4.5,17 9.5,10 14.5,17" style="stroke-width: 1.6; stroke: #070; fill: none"/><line x1="9.5" y1="17" x2="8.5" y2="19" style="stroke-width: 1.3; stroke: #070; fill: none"/><path d="M 13.5,11.5 A 4,5 0 0 1 5.5,11.5 A 4,5 0 0 1 13.5,11.5 Z" style="stroke: #070; fill: #2c3"/><path d="M 11.15,6.75 A 4,5 0 0 1 12.04,13.74 A 4,5 0 0 1 6.45,14.85" style="stroke: #0709; fill: none"/>',
	},
	canvas: {
		width: 20,
		height: 20,
		innerSVG:
			'<rect x="3" y="2" width="14" height="16" style="stroke: none; fill: #333"/><rect x="4" y="3" width="12" height="14" style="stroke: none; fill: #fff"/><rect x="5.5" y="5.5" width="6" height="6" style="stroke: #00cc; fill: #00c8"/><circle cx="11" cy="11" r="3.5" style="stroke: #c00c; fill: #c008"/>',
	},
	tutorial: {
		width: 20,
		height: 20,
		innerSVG:
			'<path d="M 5 20 L 9 2 L 11 2 L 15 20" style="stroke-width: 3; stroke: #666; fill: none"/><polyline points="5,20 9,2 11,2 15,20" style="stroke-width: 2; stroke: #db7; fill: none"/><rect x="1.5" y="2.5" width="17" height="12" style="stroke: none; fill: #666"/><rect x="2" y="3" width="16" height="11" style="stroke: none; fill: #db7"/><rect x="3" y="4" width="14" height="9" style="stroke: none; fill: #000"/><polyline points="5,6 7,8 5,10" style="stroke: #fff; fill: none"/>',
	},
};
